[package]
name = "covalent"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binaryen = "0.12.1"
# inkwell = { version = "0.3.0", features = ["llvm14-0"] }
